baseURL = "http://neacajui.com.br"
languageCode = "pt-BR"
title = "NeaCajuí - Empresa júnior"
author = "https://www.catiuespi.com/"
theme = "terrassa"
enableRobotsTXT = true
paginate = 10

[params]
    description = "NeaCajuí - Empresa júnior | Parnaíba - PI"
    favicon = "favicon.ico"
    logo = "neacajui-logo.jpg"

[params.hero]
    textColor = "#038A24" # Empty for default color

[params.cta] # Call To Action
    show = true
    cta = "Contato"
    link = "contato" # Relative URL

[params.separator] # Separators between sections on the home page
    show = false

[params.fa] # Font Awesome options
    version = "5.7.2"
    integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

[params.form] # Contact form
    netlify = true
    action = "https://formspree.io/your@email.com"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Nome"
    inputNamePlaceholder = "Seu Nome"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Insira seu email"
    inputMsgName = "message"
    inputMsgLabel = "Qual sua mensagem?"
    inputMsgLength = 750
    inputSubmitValue = "Enviar"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "Segunda-Feira, Janeiro, 2006"

[params.contact] # Contact info
    email = "examplodeemail@gmail.com"
    phone = "(XX) X XXXX-XXXX"
    skype = ""
    address = "Parnaíba - Piauí"

[params.social]
    twitter = "https://twitter.com/john"
    facebook = "https://facebook.com/john"
    gitlab = ""
    instagram = "https://instagram.com/john"
    pinterest = ""
    youtube = ""
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""
    flickr = ""
    "500px" = ""

[params.copy] # Copyright
    copy = "CATI - Centro Acadêmico de Tecnologia e Inovação" # Empty for default content

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true

[params.languageSwitcher]
    show = true
